### ISSUE TITLE
Task 1 - Implement classical MergeSort recursively. 

### ISSUE THREAD

**Issue by marcusskjold** [marcusskjold/AAexam#1]
Any variant is fine. One obvious place to start is the detailed description in Chapter 2.2 of Sedgewick and Wayne “Algorithms” [3], “Top-down MergeSort”. We suggest that you stick to the paradigm of abstract in-place merging as in Chapter 2.2 of [3]. Instead of the functions not returning anything, make them return the total number of comparisons performed.

[3] Robert Sedgewick and Kevin Wayne. Algorithms, 4th Edition. Addison-Wesley, 2011.

**Comment by AndreasRigetBagge** [comment]
Current goals: Make mergesort and tests.

- Ensure that no of comparisons returned
- Design relevant test cases
- Create unit tests -> ensure correctness
