### ISSUE TITLE
Task 9: Investigate the influence of the parameter c and the pre-sortedness of the input on the running time

### ISSUE THREAD

**Issue by marcusskjold** [marcusskjold/AAexam#9]
Design and conduct an experiment to investigate the influence of the parameter c and the pre-sortedness of the input on the running time and number of comparisons.

Perform this experiment for the four variants and discuss the following questions:

1. How should you choose the parameter c? Are there differences between the variants?
2. What differences in adaptiveness do you see between the algorithms?

**Comment by AndreasRigetBagge** [comment]
Also closed.
